name: Sync Documenti (compilati) a repo Atlas

on:
  push:
    paths:
      - "Candidatura/**"
      - "PB/**"
      - "RTB/**"
      - "Presentazioni/**"
    branches:
      - main
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Documenti repo
        uses: actions/checkout@v4

      # --- SOLUZIONE VELOCITÀ (CACHE EFFICIENTE) ---
      - name: Set up TeX Live (con cache)
        uses: zauguin/install-texlive@v4
        with:
          # Lista di pacchetti aggiornata per essere più robusta
          packages: >-
            collection-fontsrecommended
            collection-latexextra
            collection-pictures
            babel-italian

      # --- Compilazione ---
      - name: Compila i file .tex in PDF (mantenendo la struttura)
        run: |
          echo "Compilo tutti i file .tex trovati..."
          find . -name "*.tex" -print0 | while IFS= read -r -d '' texfile; do
            echo "Compilando $texfile..."
            OUTPUT_DIR=$(dirname "$texfile")
            pdflatex -interaction=nonstopmode -output-directory="$OUTPUT_DIR" "$texfile"
            pdflatex -interaction=nonstopmode -output-directory="$OUTPUT_DIR" "$texfile"
          done
          echo "Compilazione terminata."

      # --- Deploy  ---
      - name: Clona la repo del sito web
        run: |
          git clone https://x-access-token:${{ secrets.SITE_REPO_TOKEN }}@github.com/AtlasTeam9/Atlas.git site

      # --- Sincronizzazione ---
      - name: Sincronizza i PDF compilati nel sito
        run: |
          echo "Sincronizzo i PDF in site/docs..."

          mkdir -p site/docs

          for dir in Candidatura PB RTB Presentazioni; do
            if [ -d "$dir" ]; then
              echo "Sincronizzando cartella: $dir"
              rsync -av \
                    --include="*/" \
                    --include="*.pdf" \
                    --exclude="*" \
                    "$dir/" "site/docs/$dir/"
            else
              echo "Cartella $dir non presente, la salto"
            fi
          done
          
          if [ -z "$(ls -A site/docs)" ]; then
            touch site/docs/.gitkeep
          fi
          echo "Contenuto di site/docs dopo rsync:"
          ls -laR site/docs

      # --- Pulizia ---
      - name: Pulisci i PDF da repo sorgente
        run: |
          echo "Pulisco i file compilati dal repository sorgente..."
          for dir in Candidatura PB RTB Presentazioni; do
            if [ -d "$dir" ]; then
              find "$dir" -name "*.pdf" -delete
              find "$dir" -name "*.aux" -delete
              find "$dir" -name "*.log" -delete
              find "$dir" -name "*.out" -delete
              find "$dir" -name "*.toc" -delete
            fi
          done

      # --- Commit Finale ---
      - name: Commit e push delle modifiche
        run: |
          cd site
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add docs/
          
          git commit -m "Sync new compiled docs" || echo "No changes to commit"
          git push

      # --- STEP FINALE: Invia il segnale di Deploy ---
      - name: Trigger Deploy su Atlas
        env:
          GITHUB_TOKEN: ${{ secrets.SITE_REPO_TOKEN }}
          REPO_OWNER: "AtlasTeam9"
          REPO_NAME: "Atlas"
          EVENT_TYPE: "docs-updated" # Deve corrispondere a quello in pages.yml
        run: |
          echo "Invio segnale 'repository_dispatch' a $REPO_OWNER/$REPO_NAME"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/dispatches \
            -d '{"event_type":"$EVENT_TYPE"}'
